
	#include <a_samp>
	

//anti cheat aufa command block biar pemain ga bisa akses
CMD:rem(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ rem ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}
CMD:whack(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ whack ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}
CMD:fcrash(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ fcrash ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:dgun(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ dgun ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}
CMD:skema(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ skema ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:fr(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ fr ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:pgun(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ pgun ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:xgun(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ xgun ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:flip(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ flip ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:am(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ am ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:fly(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ fly ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:dmg(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ dmg ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:anti(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ anti ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:fakespawn(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ fakespawn ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:jack(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ jack ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}

CMD:tp(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ tp ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}


CMD:tr(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [  tr ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}


CMD:fspawn(playerid, params[])
{
	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ fspawn ]", pData[playerid][pName]);
 	Kick(playerid);
	return 1;
}


// CMD:hp(playerid, params[])
// {
// 	SendClientMessageToAllEx(COLOR_RED, "AntiCmd: {778899}%s terkick karena menggunakan command ilegal [ hp ]", pData[playerid][pName]);
//  	Kick(playerid);
// 	return 1;
// }