#define OWNER_SERVER		"YOGAZZ"

#define PROJECT_FOUNDER 		"Yogazz_Alguero"

stock YConnect()
{
    print("===============================");
    print("GAMEMODE KAPUNG ROLEPLAY REMAKE BY: YOGAZZ");
    print("SUBSCRIBE CHANNEL 'Yog AZZ'");
    print("===============================");
    print("===============================");
}

stock Testing()
{
    SendClientMessageToAll(-1, "{0080FF}GAMEMODE INI DIREMAKE OLEH{FFFFFF} YOGAZZ");
}

stock Kencing(playerid)
{
	ApplyAnimation(playerid,"PAULNMAC","piss_in", 4.1,0,1,1,1,1,1);
	SetPlayerAttachedObject(playerid, 0, 18676, 1, -1.900000, 0.300000, 0.000000, 148.199584, 90.099914, -55.199981, 1.000000, -9.899993, 1.000000);
	SetPlayerAttachedObject(playerid, 1, 19086, 8, -0.049768, -0.014062, -0.108385, 87.458297, 263.478149, 184.123764, 0.622413, 1.041609, 1.012785 );
}










